# Generated by Django 5.1 on 2026-01-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrentBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_balance", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TrackingHistroy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "expense_type",
                    models.CharField(
                        choices=[("CREDIT", "CREDIT"), ("DEBIT", "DEBIT")],
                        max_length=200,
                    ),
                ),
                ("desctiption", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "CurrentBalance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.currentbalance",
                    ),
                ),
            ],
        ),
    ]
