# Generated by Django 5.1 on 2026-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackinghistroy",
            old_name="CurrentBalance",
            new_name="current_balance",
        ),
        migrations.RemoveField(
            model_name="trackinghistroy",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="trackinghistroy",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
