# Generated by Django 5.1 on 2026-01-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracker",
            "0002_rename_currentbalance_trackinghistroy_current_balance_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_info", models.TextField()),
                ("request_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
