# Generated by Django 5.1 on 2026-01-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_requestlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlogs",
            name="request_method",
            field=models.CharField(default="get", max_length=100),
            preserve_default=False,
        ),
    ]
